apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.microservice}}-{{.Values.db.label}}-config
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.microservice}}
    tier: {{.Values.db.label}}
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
