# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.db.writelb}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.microservice}}
    tier: {{.Values.db.label}}
spec:
  ports:
  - name: mysql
    port: {{.Values.db.port}}
  clusterIP: None
  selector:
    app: {{.Values.microservice}}
    tier: {{.Values.db.label}}